import { User, ServiceProvider } from './types'

export const DEMO_ACCOUNTS = {
  superadmin: {
    id: 'demo-superadmin',
    email: 'superadmin@proenpoche.ca',
    name: 'Super Administrateur',
    role: 'superadmin' as const,
    createdAt: '2024-01-01T00:00:00Z',
  },
  admin: {
    id: 'demo-admin',
    email: 'admin@proenpoche.ca',
    name: 'Administrateur',
    role: 'admin' as const,
    createdAt: '2024-01-01T00:00:00Z',
  },
  client: {
    id: 'demo-client',
    email: 'client@proenpoche.ca',
    name: 'Marie Tremblay',
    role: 'client' as const,
    createdAt: '2024-01-01T00:00:00Z',
  },
  provider: {
    id: 'demo-provider',
    email: 'prestataire@proenpoche.ca',
    name: 'Jean Lefebvre',
    role: 'provider' as const,
    bio: 'Plombier professionnel avec plus de 15 ans d\'expérience. Spécialisé dans les réparations résidentielles et commerciales.',
    services: ['Plomberie', 'Réparations d\'urgence', 'Installation'],
    location: 'Montréal',
    availability: 'Lun-Ven, 8h-18h',
    hourlyRate: 75,
    rating: 4.8,
    reviewCount: 42,
    verified: true,
    createdAt: '2024-01-01T00:00:00Z',
  }
}

export const DEMO_PROVIDERS: ServiceProvider[] = [
  {
    id: 'provider-1',
    email: 'sophie.martin@email.ca',
    name: 'Sophie Martin',
    role: 'provider',
    bio: 'Designer d\'intérieur passionnée avec 8 ans d\'expérience. Je transforme vos espaces en lieux de vie harmonieux et fonctionnels.',
    services: ['Design d\'intérieur', 'Consultation', 'Décoration'],
    location: 'Montréal',
    availability: 'Mar-Sam, 10h-17h',
    hourlyRate: 85,
    rating: 4.9,
    reviewCount: 28,
    verified: true,
    createdAt: '2024-01-15T00:00:00Z',
    profession: 'Designer d\'Intérieur Certifiée',
    experience: '8 ans d\'expérience en design résidentiel et commercial. Spécialisée dans les espaces contemporains et minimalistes.',
    certifications: ['Certification en Design d\'Intérieur (NCIDQ)', 'LEED Green Associate'],
    languages: ['Français', 'Anglais'],
    responseTime: '2 heures',
  },
  {
    id: 'provider-2',
    email: 'pierre.dubois@email.ca',
    name: 'Pierre Dubois',
    role: 'provider',
    bio: 'Électricien certifié spécialisé dans les installations résidentielles et les rénovations électriques.',
    services: ['Électricité', 'Installation', 'Dépannage'],
    location: 'Québec',
    availability: 'Lun-Ven, 7h-16h',
    hourlyRate: 80,
    rating: 4.7,
    reviewCount: 35,
    verified: true,
    createdAt: '2024-01-10T00:00:00Z',
    profession: 'Maître Électricien',
    experience: '12 ans d\'expérience. Spécialisé en systèmes résidentiels et commerciaux, domotique et rénovations.',
    certifications: ['Licence de Maître Électricien du Québec', 'Certification RBQ'],
    languages: ['Français'],
    responseTime: '1 heure',
  },
  {
    id: 'provider-3',
    email: 'amelie.gagnon@email.ca',
    name: 'Amélie Gagnon',
    role: 'provider',
    bio: 'Photographe professionnelle spécialisée dans les portraits, événements et photographie commerciale.',
    services: ['Photographie', 'Portraits', 'Événements'],
    location: 'Ottawa',
    availability: 'Mer-Dim, flexible',
    hourlyRate: 120,
    rating: 5.0,
    reviewCount: 18,
    verified: true,
    createdAt: '2024-02-01T00:00:00Z',
    profession: 'Photographe Professionnelle',
    experience: '6 ans d\'expérience en photographie événementielle et commerciale. Portfolio primé dans plusieurs compétitions.',
    certifications: ['Diplôme en Photographie Professionnelle', 'Membre de la PPOC'],
    languages: ['Français', 'Anglais'],
    responseTime: '4 heures',
  },
  {
    id: 'provider-4',
    email: 'marc.roy@email.ca',
    name: 'Marc Roy',
    role: 'provider',
    bio: 'Entraîneur personnel certifié, je vous aide à atteindre vos objectifs de santé et de fitness.',
    services: ['Entraînement personnel', 'Nutrition', 'Coaching'],
    location: 'Toronto',
    availability: 'Lun-Sam, 6h-20h',
    hourlyRate: 60,
    rating: 4.8,
    reviewCount: 52,
    verified: true,
    createdAt: '2024-01-20T00:00:00Z',
    profession: 'Entraîneur Personnel Certifié',
    experience: '10 ans d\'expérience en conditionnement physique et nutrition sportive. Plus de 200 clients accompagnés.',
    certifications: ['CANFITPRO Certified Personal Trainer', 'Nutritionniste Sportif'],
    languages: ['Français', 'Anglais'],
    responseTime: '3 heures',
  },
  {
    id: 'provider-5',
    email: 'isabelle.leblanc@email.ca',
    name: 'Isabelle Leblanc',
    role: 'provider',
    bio: 'Service de ménage professionnel et écologique. Votre maison propre et saine est ma priorité.',
    services: ['Ménage', 'Nettoyage en profondeur', 'Entretien'],
    location: 'Vancouver',
    availability: 'Lun-Ven, 8h-17h',
    hourlyRate: 45,
    rating: 4.6,
    reviewCount: 64,
    verified: true,
    createdAt: '2024-01-05T00:00:00Z',
    profession: 'Spécialiste en Nettoyage Écologique',
    experience: '5 ans d\'expérience en entretien ménager résidentiel et commercial. Utilisation exclusive de produits écologiques.',
    certifications: ['Formation en Nettoyage Écologique', 'Certification Green Seal'],
    languages: ['Français', 'Anglais'],
    responseTime: '6 heures',
  },
  {
    id: 'provider-6',
    email: 'francois.cote@email.ca',
    name: 'François Côté',
    role: 'provider',
    bio: 'Tuteur expérimenté en mathématiques et sciences pour tous les niveaux scolaires.',
    services: ['Tutorat', 'Mathématiques', 'Sciences'],
    location: 'Calgary',
    availability: 'Lun-Ven, 15h-21h, Sam 9h-17h',
    hourlyRate: 55,
    rating: 4.9,
    reviewCount: 41,
    verified: true,
    createdAt: '2024-02-10T00:00:00Z',
    profession: 'Tuteur Académique',
    experience: '7 ans d\'expérience en enseignement privé. Spécialisé dans la préparation aux examens et le soutien scolaire.',
    certifications: ['Baccalauréat en Éducation', 'Certification en Tutorat Professionnel'],
    languages: ['Français', 'Anglais'],
    responseTime: '2 heures',
  },
]

export const CANADIAN_CITIES = [
  'Toutes les villes',
  'Montréal',
  'Toronto',
  'Vancouver',
  'Calgary',
  'Ottawa',
  'Edmonton',
  'Québec',
  'Winnipeg',
  'Hamilton',
  'Kitchener',
  'London',
  'Victoria',
  'Halifax',
  'Oshawa',
  'Windsor',
]

export const SERVICE_CATEGORIES = [
  'Tous les services',
  'Plomberie',
  'Électricité',
  'Ménage',
  'Tutorat',
  'Entraînement personnel',
  'Photographie',
  'Consultation',
  'Design d\'intérieur',
  'Décoration',
  'Réparations',
]
